services:
  - docker

env:
  - UNITY_VERSION=2019.2.7f2 UNITY_HASH=c96f78eb5904

script:
  - docker build -t unity .
  - docker tag unity stanov/unity:$UNITY_VERSION
  - docker login --username stanov --password $DOCKER_HUB_PASSWORD
  - docker push stanov/unity:$UNITY_VERSION

