services:
  - docker

env:
  - UNITY_VERSION=2019.2.9f1 UNITY_HASH=ebce4d76e6e8

before_script:
  - set -e
  - sudo apt install libxml2-utils -y
  - docker build -t unity --build-arg UNITY_VERSION=$UNITY_VERSION --build-arg UNITY_HASH=$UNITY_HASH .
  
script:
  - docker run unity bash -c "cd /; unity -createManualActivationFile > /dev/null; cat Unity_v${UNITY_VERSION}.alf" | xmllint --format --output UnityLicenseRequest.alf -
  - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
  - docker tag unity ${DOCKER_HUB_USERNAME}/unity:${UNITY_VERSION}-no-license
  - docker push ${DOCKER_HUB_USERNAME}/unity:${UNITY_VERSION}-no-license
  - echo "Use the XML below as a license request file here https://license.unity3d.com/manual , then put the license file into stanov/unity-docker-with-license repo."
  - cat UnityLicenseRequest.alf
