services:
  - docker

env:
  - UNITY_VERSION=2019.2.7f2 UNITY_HASH=c96f78eb5904

script:
  - docker build -t stanov/unity:$UNITY_VERSION --build-arg UNITY_VERSION=$UNITY_VERSION --build-arg UNITY_HASH=$UNITY_HASH .
  - echo $DOCKER_HUB_PASSWORD | docker login --username stanov --password-stdin
  - docker push stanov/unity:$UNITY_VERSION

